---
- hosts: all
  #connection: local

  roles:
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']

    - role: vim
      tags: ['vim']

    - role: snap
      tags: ['snap']

    - role: nvm
      nvm_node_versions: 
        - 8.2.0
        - 6.11.1
      nvm_global_packages:
        - react-native-cli
      tags: ['nvm']

    - role: vagrant
      vagrant_force_install: no
      tags: ['vagrant']

    - role: androidstudio
      tags: ['umake']

    - role: dropbox
      tags: ['dropbox']

    - role: docker
      tags: ['docker']

    - role: dockercompose
      tags: ['dockercompose']
    
  tasks:
    - include_vars: "main.yml"
      tags: 
        - apt
        - snap_packages

    - name: Add apt repo keys
      apt_key: 
        url: "{{ item }}"
        state: present
      become: yes
      with_items: "{{ apt_keys }}"
      tags: ['apt']

    - name: Add apt repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      become: yes
      with_items: "{{ apt_repositories }}"
      tags: ['apt']

    - name: Update apt cache
      become: yes
      command: apt update
      tags: ['apt']

    - name: Install packages with apt
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        allow_unauthenticated: yes
      become: yes
      with_items: "{{ apt_packages }}"
      tags: ['apt']

    - name: Install packages with snapd
      command: snap install {{ item }}
      become: yes
      with_items: "{{ snap_packages }}"
      tags: ['snap_packages']
