---
dotfiles_repo: "https://github.com/evanhsu/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "~/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .bash_aliases
  - .bashrc
  - .gitconfig
  - .profile
  - .tmux.conf
  - .vimrc
