---

- name: install NodeJS versions with nvm
  shell: "source ~/.nvm/nvm.sh && nvm install {{ nvm_node_version }}"
  register: output
  changed_when: "'already installed.' not in output.stderr"
  args:
    executable: /bin/bash
  with_items: "{{ nvm_node_versions }}"
  loop_control:
    loop_var: nvm_node_version

- name: Set default node version in .profile
  lineinfile:
    path: ~/.profile
    regexp: '\s*nvm alias default.*'
    line: "    nvm alias default {{ nvm_node_versions[0] }}"
    state: present
    insertafter: '.*\$NVM_DIR/nvm\.sh.*'

- name: Specify nvm use default in .profile
  lineinfile:
    path: ~/.profile
    regexp: '\s*nvm use default'
    line: '    nvm use default'
    state: present
    insertafter: '\s*nvm alias default.*'

- name: create alias directory
  file: path="~/alias" state=directory
  become: false


