---

- name: install NodeJS versions with nvm
  shell: "source ~/.nvm/nvm.sh && nvm install {{ nvm_node_version }}"
  register: output
  changed_when: "'already installed.' not in output.stderr"
  args:
    executable: /bin/bash
  with_items: "{{ nvm_node_versions }}"
  loop_control:
    loop_var: nvm_node_version

- name: Set default node version in .profile
  lineinfile:
    path: ~/.profile
    line: "nvm alias default {{ nvm_node_versions[0] }}"
    state: present

- name: Specify nvm use default in .profile
  lineinfile:
    path: ~/.profile
    line: 'nvm use default'
    insertafter: 'nvm alias default .*'

- name: create alias directory
  file: path="~/alias" state=directory
  become: false


